/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.unal.Reto5.vista;


import co.edu.unal.Reto5.Reto5Application;
import co.edu.unal.Reto5.SpringContext;
import co.edu.unal.Reto5.modelos.Pelicula;
import co.edu.unal.Reto5.modelos.Serie;
import co.edu.unal.Reto5.repositorios.RepositorioContenidos;
import co.edu.unal.Reto5.repositorios.RepositorioPelicula;
import co.edu.unal.Reto5.repositorios.RepositorioSerie;
import co.edu.unal.Reto5.repositorios.RepositorioUsuario;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Optional;
import java.util.Set;

import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author Felipe
 */
public class RedflixForm extends javax.swing.JFrame {

    RepositorioSerie repositorioSerie;
    RepositorioPelicula repositorioPelicula;
    RepositorioUsuario repositorioUsuario;
    RepositorioContenidos repositorioContenidos;
    

    public RedflixForm() {
        initComponents();
        String[] args = {};
        Reto5Application.runSpringServer(args);
        repositorioSerie = SpringContext.getBean(RepositorioSerie.class);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoBotonesUsuario = new javax.swing.ButtonGroup();
        BuscarSeries1 = new javax.swing.JButton();
        RedflixPanel = new javax.swing.JTabbedPane();
        Inicio = new javax.swing.JPanel();
        Intro = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        AgregarSerie = new javax.swing.JButton();
        AgregarPelicula = new javax.swing.JButton();
        Busqueda = new javax.swing.JButton();
        Imagen = new javax.swing.JLabel();
        AgregarUsuario = new javax.swing.JButton();
        UsuariosInterface = new javax.swing.JPanel();
        Aceptar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        RegistroUsuarios = new javax.swing.JPanel();
        LabelNombreReg = new javax.swing.JLabel();
        IngresoNombreReg = new javax.swing.JTextField();
        LabelApellidoReg = new javax.swing.JLabel();
        IngresoApellidoReg = new javax.swing.JTextField();
        LabelEmailReg = new javax.swing.JLabel();
        LabelUsuarioReg = new javax.swing.JLabel();
        LabelContrasena = new javax.swing.JLabel();
        IngresoContrasenaReg = new javax.swing.JPasswordField();
        IngresoEmailReg = new javax.swing.JTextField();
        IngresoUsuarioReg = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        RadioRegistrarUsu = new javax.swing.JRadioButton();
        RadioActualizarUsu = new javax.swing.JRadioButton();
        jbBuscar = new javax.swing.JButton();
        PeliculasInterface = new javax.swing.JPanel();
        AceptarPeliculas = new javax.swing.JButton();
        CancelarPeliculas = new javax.swing.JButton();
        RegistroPeliculas = new javax.swing.JPanel();
        LabelTituloPelReg = new javax.swing.JLabel();
        IngresoTituloPelReg = new javax.swing.JTextField();
        LabelResumenPelReg = new javax.swing.JLabel();
        IngresoResumenPelReg = new javax.swing.JTextField();
        LabelFechaPelReg = new javax.swing.JLabel();
        LabelDirectorPelReg = new javax.swing.JLabel();
        IngresoFechaPelReg = new javax.swing.JTextField();
        IngresoDirectorPelReg = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        RadioRegistrarPel = new javax.swing.JRadioButton();
        RadioActualizarPel = new javax.swing.JRadioButton();
        EliminarPel = new javax.swing.JRadioButton();
        SeriesInterface = new javax.swing.JPanel();
        RegistroSeries = new javax.swing.JPanel();
        LabelTituloSerReg = new javax.swing.JLabel();
        IngresoTituloSerReg = new javax.swing.JTextField();
        LabelEpisodiosSerReg = new javax.swing.JLabel();
        IngresoEpisodiosSerReg = new javax.swing.JTextField();
        LabelTemporadaSerReg = new javax.swing.JLabel();
        IngresoTemporadasSerReg = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        BuscarSeries = new javax.swing.JButton();
        ActualizarSeries = new javax.swing.JButton();
        Registrar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        BusquedaInterface = new javax.swing.JPanel();
        LabelBusqueda = new javax.swing.JLabel();
        IngresoBusqueda = new javax.swing.JTextField();
        Buscar = new javax.swing.JButton();
        CancelarBusqueda = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        RadioSerBus = new javax.swing.JRadioButton();
        RadioPelBus = new javax.swing.JRadioButton();
        RadioBusUsuario = new javax.swing.JRadioButton();
        jlNotificacion = new javax.swing.JLabel();
        jlTemporadas = new javax.swing.JLabel();
        jlEpisodios = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtID = new javax.swing.JTextField();
        jltitulo = new javax.swing.JLabel();

        GrupoBotonesUsuario.add(RadioRegistrarUsu);
        GrupoBotonesUsuario.add(RadioActualizarUsu);

        BuscarSeries1.setText("Buscar");
        BuscarSeries1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarSeries1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 400));

        RedflixPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de búsqueda"));

        Intro.setText("Bienvenido a la aplicación de redflixApp, lo mejor en streaming.");

        jLabel1.setText("Por favor seleccione la opción que desea usar:");

        AgregarSerie.setText("Agregar/Modificar Serie");
        AgregarSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarSerieActionPerformed(evt);
            }
        });

        AgregarPelicula.setText("Agregar/Modificar Película");
        AgregarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarPeliculaActionPerformed(evt);
            }
        });

        Busqueda.setText("Realizar una búsqueda");
        Busqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusquedaActionPerformed(evt);
            }
        });

        Imagen.setText(null);

        AgregarUsuario.setText("Agregar/Modificar Usuario");
        AgregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InicioLayout = new javax.swing.GroupLayout(Inicio);
        Inicio.setLayout(InicioLayout);
        InicioLayout.setHorizontalGroup(
            InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InicioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Imagen)
                .addGap(333, 333, 333))
            .addGroup(InicioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Intro)
                    .addComponent(jLabel1)
                    .addGroup(InicioLayout.createSequentialGroup()
                        .addGroup(InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(AgregarSerie, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AgregarUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AgregarPelicula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Busqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        InicioLayout.setVerticalGroup(
            InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicioLayout.createSequentialGroup()
                .addComponent(Intro)
                .addGap(60, 60, 60)
                .addComponent(Imagen)
                .addGap(103, 103, 103)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgregarUsuario)
                    .addComponent(AgregarPelicula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgregarSerie)
                    .addComponent(Busqueda))
                .addContainerGap(129, Short.MAX_VALUE))
        );

        RedflixPanel.addTab("Inicio", Inicio);

        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        RegistroUsuarios.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro"));
        RegistroUsuarios.setName("Registro/Actualización"); // NOI18N
        RegistroUsuarios.setPreferredSize(new java.awt.Dimension(182, 200));

        LabelNombreReg.setText("Nombres:");

        LabelApellidoReg.setText("Apellidos:");

        LabelEmailReg.setText("Email:");

        LabelUsuarioReg.setText("Usuario:");

        LabelContrasena.setText("Contraseña:");

        IngresoUsuarioReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresoUsuarioRegActionPerformed(evt);
            }
        });
        IngresoUsuarioReg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                IngresoUsuarioRegKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout RegistroUsuariosLayout = new javax.swing.GroupLayout(RegistroUsuarios);
        RegistroUsuarios.setLayout(RegistroUsuariosLayout);
        RegistroUsuariosLayout.setHorizontalGroup(
            RegistroUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RegistroUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistroUsuariosLayout.createSequentialGroup()
                        .addGroup(RegistroUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LabelEmailReg)
                            .addComponent(LabelUsuarioReg)
                            .addComponent(LabelNombreReg)
                            .addComponent(LabelApellidoReg)
                            .addComponent(LabelContrasena)
                            .addComponent(IngresoNombreReg, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(IngresoApellidoReg)
                            .addComponent(IngresoContrasenaReg))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(IngresoEmailReg)
                    .addComponent(IngresoUsuarioReg, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        RegistroUsuariosLayout.setVerticalGroup(
            RegistroUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelNombreReg)
                .addGap(1, 1, 1)
                .addComponent(IngresoNombreReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelApellidoReg)
                .addGap(4, 4, 4)
                .addComponent(IngresoApellidoReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelEmailReg)
                .addGap(3, 3, 3)
                .addComponent(IngresoEmailReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelUsuarioReg)
                .addGap(1, 1, 1)
                .addComponent(IngresoUsuarioReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelContrasena)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IngresoContrasenaReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        RadioRegistrarUsu.setText("Registrar");
        RadioRegistrarUsu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RadioRegistrarUsuMouseClicked(evt);
            }
        });
        RadioRegistrarUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioRegistrarUsuActionPerformed(evt);
            }
        });

        RadioActualizarUsu.setText("Actualizar");
        RadioActualizarUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioActualizarUsuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RadioActualizarUsu)
                    .addComponent(RadioRegistrarUsu))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(RadioRegistrarUsu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RadioActualizarUsu)
                .addGap(24, 24, 24))
        );

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UsuariosInterfaceLayout = new javax.swing.GroupLayout(UsuariosInterface);
        UsuariosInterface.setLayout(UsuariosInterfaceLayout);
        UsuariosInterfaceLayout.setHorizontalGroup(
            UsuariosInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsuariosInterfaceLayout.createSequentialGroup()
                .addGroup(UsuariosInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UsuariosInterfaceLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RegistroUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbBuscar))
                    .addGroup(UsuariosInterfaceLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Aceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Cancelar)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        UsuariosInterfaceLayout.setVerticalGroup(
            UsuariosInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsuariosInterfaceLayout.createSequentialGroup()
                .addGroup(UsuariosInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UsuariosInterfaceLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(UsuariosInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RegistroUsuarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UsuariosInterfaceLayout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92)))
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(UsuariosInterfaceLayout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jbBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(UsuariosInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Aceptar)
                    .addComponent(Cancelar))
                .addGap(60, 60, 60))
        );

        RedflixPanel.addTab("Usuarios", UsuariosInterface);
        UsuariosInterface.getAccessibleContext().setAccessibleParent(AgregarUsuario);

        AceptarPeliculas.setText("Aceptar");
        AceptarPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarPeliculasActionPerformed(evt);
            }
        });

        CancelarPeliculas.setText("Cancelar");
        CancelarPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarPeliculasActionPerformed(evt);
            }
        });

        RegistroPeliculas.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro"));
        RegistroPeliculas.setName("Registro/Actualización"); // NOI18N
        RegistroPeliculas.setPreferredSize(new java.awt.Dimension(182, 200));

        LabelTituloPelReg.setText("Título:");

        LabelResumenPelReg.setText("Resumen:");

        LabelFechaPelReg.setText("Fecha de lanzamiento:");

        LabelDirectorPelReg.setText("Director:");

        javax.swing.GroupLayout RegistroPeliculasLayout = new javax.swing.GroupLayout(RegistroPeliculas);
        RegistroPeliculas.setLayout(RegistroPeliculasLayout);
        RegistroPeliculasLayout.setHorizontalGroup(
            RegistroPeliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroPeliculasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RegistroPeliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistroPeliculasLayout.createSequentialGroup()
                        .addGroup(RegistroPeliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LabelFechaPelReg)
                            .addComponent(LabelDirectorPelReg)
                            .addComponent(LabelTituloPelReg)
                            .addComponent(LabelResumenPelReg)
                            .addComponent(IngresoTituloPelReg, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(IngresoResumenPelReg))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(IngresoFechaPelReg)
                    .addComponent(IngresoDirectorPelReg, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        RegistroPeliculasLayout.setVerticalGroup(
            RegistroPeliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroPeliculasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelTituloPelReg)
                .addGap(1, 1, 1)
                .addComponent(IngresoTituloPelReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelResumenPelReg)
                .addGap(4, 4, 4)
                .addComponent(IngresoResumenPelReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelFechaPelReg)
                .addGap(3, 3, 3)
                .addComponent(IngresoFechaPelReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelDirectorPelReg)
                .addGap(1, 1, 1)
                .addComponent(IngresoDirectorPelReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        RadioRegistrarPel.setText("Registrar");
        RadioRegistrarPel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RadioRegistrarPelMouseClicked(evt);
            }
        });
        RadioRegistrarPel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioRegistrarPelActionPerformed(evt);
            }
        });

        RadioActualizarPel.setText("Actualizar");
        RadioActualizarPel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioActualizarPelActionPerformed(evt);
            }
        });

        EliminarPel.setText("Eliminar");
        EliminarPel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarPelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RadioActualizarPel)
                    .addComponent(RadioRegistrarPel)
                    .addComponent(EliminarPel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(RadioRegistrarPel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RadioActualizarPel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EliminarPel))
        );

        javax.swing.GroupLayout PeliculasInterfaceLayout = new javax.swing.GroupLayout(PeliculasInterface);
        PeliculasInterface.setLayout(PeliculasInterfaceLayout);
        PeliculasInterfaceLayout.setHorizontalGroup(
            PeliculasInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PeliculasInterfaceLayout.createSequentialGroup()
                .addGroup(PeliculasInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PeliculasInterfaceLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RegistroPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PeliculasInterfaceLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AceptarPeliculas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CancelarPeliculas)))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        PeliculasInterfaceLayout.setVerticalGroup(
            PeliculasInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PeliculasInterfaceLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PeliculasInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RegistroPeliculas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PeliculasInterfaceLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(PeliculasInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AceptarPeliculas)
                    .addComponent(CancelarPeliculas))
                .addGap(60, 60, 60))
        );

        RedflixPanel.addTab("Películas", PeliculasInterface);

        RegistroSeries.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro/Actualización"));
        RegistroSeries.setName("Registro/Actualización"); // NOI18N
        RegistroSeries.setPreferredSize(new java.awt.Dimension(182, 200));

        LabelTituloSerReg.setText("Título:");

        LabelEpisodiosSerReg.setText("Episodios:");

        LabelTemporadaSerReg.setText("Temporadas:");

        javax.swing.GroupLayout RegistroSeriesLayout = new javax.swing.GroupLayout(RegistroSeries);
        RegistroSeries.setLayout(RegistroSeriesLayout);
        RegistroSeriesLayout.setHorizontalGroup(
            RegistroSeriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroSeriesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RegistroSeriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistroSeriesLayout.createSequentialGroup()
                        .addGroup(RegistroSeriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LabelTemporadaSerReg)
                            .addComponent(LabelTituloSerReg)
                            .addComponent(LabelEpisodiosSerReg)
                            .addComponent(IngresoTituloSerReg, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(IngresoEpisodiosSerReg))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(IngresoTemporadasSerReg))
                .addContainerGap())
        );
        RegistroSeriesLayout.setVerticalGroup(
            RegistroSeriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroSeriesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelTituloSerReg)
                .addGap(1, 1, 1)
                .addComponent(IngresoTituloSerReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelEpisodiosSerReg)
                .addGap(4, 4, 4)
                .addComponent(IngresoEpisodiosSerReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelTemporadaSerReg)
                .addGap(3, 3, 3)
                .addComponent(IngresoTemporadasSerReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 94, Short.MAX_VALUE)
        );

        BuscarSeries.setText("Buscar");
        BuscarSeries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarSeriesActionPerformed(evt);
            }
        });

        ActualizarSeries.setText("Actualizar");
        ActualizarSeries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarSeriesActionPerformed(evt);
            }
        });

        Registrar.setText("Registrar");
        Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarActionPerformed(evt);
            }
        });

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SeriesInterfaceLayout = new javax.swing.GroupLayout(SeriesInterface);
        SeriesInterface.setLayout(SeriesInterfaceLayout);
        SeriesInterfaceLayout.setHorizontalGroup(
            SeriesInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SeriesInterfaceLayout.createSequentialGroup()
                .addGroup(SeriesInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SeriesInterfaceLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SeriesInterfaceLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BuscarSeries)))
                .addGap(18, 18, 18)
                .addGroup(SeriesInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RegistroSeries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(SeriesInterfaceLayout.createSequentialGroup()
                        .addComponent(ActualizarSeries)
                        .addGap(18, 18, 18)
                        .addComponent(Registrar)
                        .addGap(18, 18, 18)
                        .addComponent(Eliminar)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        SeriesInterfaceLayout.setVerticalGroup(
            SeriesInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SeriesInterfaceLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(SeriesInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RegistroSeries, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SeriesInterfaceLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)))
                .addGap(18, 29, Short.MAX_VALUE)
                .addGroup(SeriesInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Eliminar)
                    .addComponent(Registrar)
                    .addComponent(ActualizarSeries)
                    .addComponent(BuscarSeries))
                .addGap(49, 49, 49))
        );

        RedflixPanel.addTab("Series", SeriesInterface);

        LabelBusqueda.setText("Búsqueda:");

        IngresoBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresoBusquedaActionPerformed(evt);
            }
        });
        IngresoBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                IngresoBusquedaKeyPressed(evt);
            }
        });

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        CancelarBusqueda.setText("Cancelar");
        CancelarBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarBusquedaActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de búsqueda"));
        jPanel3.setMaximumSize(new java.awt.Dimension(100, 100));
        jPanel3.setName("Tipo de búsqueda"); // NOI18N

        RadioSerBus.setText("Series");
        RadioSerBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioSerBusActionPerformed(evt);
            }
        });

        RadioPelBus.setText("Películas");
        RadioPelBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioPelBusActionPerformed(evt);
            }
        });

        RadioBusUsuario.setText("Usuarios");
        RadioBusUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioBusUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RadioBusUsuario)
                    .addComponent(RadioPelBus)
                    .addComponent(RadioSerBus))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(RadioBusUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RadioPelBus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RadioSerBus)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel2.setText("ID");

        javax.swing.GroupLayout BusquedaInterfaceLayout = new javax.swing.GroupLayout(BusquedaInterface);
        BusquedaInterface.setLayout(BusquedaInterfaceLayout);
        BusquedaInterfaceLayout.setHorizontalGroup(
            BusquedaInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BusquedaInterfaceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BusquedaInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BusquedaInterfaceLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(BusquedaInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BusquedaInterfaceLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(BusquedaInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(IngresoBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                                    .addGroup(BusquedaInterfaceLayout.createSequentialGroup()
                                        .addComponent(LabelBusqueda)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(BusquedaInterfaceLayout.createSequentialGroup()
                                        .addGroup(BusquedaInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(BusquedaInterfaceLayout.createSequentialGroup()
                                                .addGap(17, 17, 17)
                                                .addComponent(jlNotificacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(jlTemporadas))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jlEpisodios)
                                        .addGap(68, 68, 68))))
                            .addGroup(BusquedaInterfaceLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jtID, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(BusquedaInterfaceLayout.createSequentialGroup()
                        .addComponent(Buscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CancelarBusqueda)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BusquedaInterfaceLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jltitulo))
        );
        BusquedaInterfaceLayout.setVerticalGroup(
            BusquedaInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BusquedaInterfaceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jltitulo)
                .addGap(8, 8, 8)
                .addGroup(BusquedaInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BusquedaInterfaceLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(BusquedaInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Buscar)
                            .addComponent(CancelarBusqueda))
                        .addContainerGap(265, Short.MAX_VALUE))
                    .addGroup(BusquedaInterfaceLayout.createSequentialGroup()
                        .addComponent(LabelBusqueda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IngresoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(BusquedaInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlTemporadas)
                        .addGap(26, 26, 26)
                        .addGroup(BusquedaInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlNotificacion)
                            .addComponent(jlEpisodios))
                        .addGap(134, 134, 134))))
        );

        RedflixPanel.addTab("Búsqueda", BusquedaInterface);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RedflixPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RedflixPanel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        if (RadioRegistrarUsu.isSelected() == true) {
            JOptionPane.showMessageDialog(null, IngresoNombreReg.getText() + IngresoApellidoReg.getText() + IngresoContrasenaReg.getText());
        }
        if (RadioActualizarUsu.isSelected()) {

        }
        RedflixPanel.setSelectedIndex(0);


    }//GEN-LAST:event_AceptarActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        IngresoNombreReg.setText(null);
        IngresoApellidoReg.setText(null);
        IngresoContrasenaReg.setText(null);
        RedflixPanel.setSelectedIndex(0);
    }//GEN-LAST:event_CancelarActionPerformed

    private void RadioActualizarUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioActualizarUsuActionPerformed
        RadioRegistrarUsu.setSelected(false);
    }//GEN-LAST:event_RadioActualizarUsuActionPerformed

    private void AgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarUsuarioActionPerformed
        RedflixPanel.setSelectedIndex(1);
    }//GEN-LAST:event_AgregarUsuarioActionPerformed

    private void BusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusquedaActionPerformed
        RedflixPanel.setSelectedIndex(4);
    }//GEN-LAST:event_BusquedaActionPerformed

    private void AgregarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarPeliculaActionPerformed
        RedflixPanel.setSelectedIndex(2);
    }//GEN-LAST:event_AgregarPeliculaActionPerformed

    private void AgregarSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarSerieActionPerformed
        RedflixPanel.setSelectedIndex(3);
    }//GEN-LAST:event_AgregarSerieActionPerformed

    private void RadioRegistrarUsuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RadioRegistrarUsuMouseClicked
        RadioActualizarUsu.setSelected(false);
    }//GEN-LAST:event_RadioRegistrarUsuMouseClicked

    private void AceptarPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarPeliculasActionPerformed
        if (RadioRegistrarPel.isSelected() == true) {
            JOptionPane.showMessageDialog(null, IngresoTituloPelReg.getText());
        }
        RedflixPanel.setSelectedIndex(0);


    }//GEN-LAST:event_AceptarPeliculasActionPerformed

    private void CancelarPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarPeliculasActionPerformed
        IngresoNombreReg.setText(null);
        IngresoApellidoReg.setText(null);
        IngresoContrasenaReg.setText(null);
        RedflixPanel.setSelectedIndex(0);
    }//GEN-LAST:event_CancelarPeliculasActionPerformed

    private void RadioRegistrarPelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RadioRegistrarPelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioRegistrarPelMouseClicked

    private void RadioActualizarPelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioActualizarPelActionPerformed
        RadioRegistrarPel.setSelected(false);
    }//GEN-LAST:event_RadioActualizarPelActionPerformed

    private void RadioRegistrarPelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioRegistrarPelActionPerformed
        RadioActualizarPel.setSelected(false);

    }//GEN-LAST:event_RadioRegistrarPelActionPerformed

    private void IngresoBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresoBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngresoBusquedaActionPerformed

    private void IngresoBusquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IngresoBusquedaKeyPressed

        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            JOptionPane.showMessageDialog(null, "Acaba de presionar la tecla enter");
        }
    }//GEN-LAST:event_IngresoBusquedaKeyPressed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        
        
    }//GEN-LAST:event_BuscarActionPerformed

    private void CancelarBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarBusquedaActionPerformed
        RedflixPanel.setSelectedIndex(0);
    }//GEN-LAST:event_CancelarBusquedaActionPerformed

    private void RadioRegistrarUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioRegistrarUsuActionPerformed
        RadioActualizarUsu.setSelected(false);
        IngresoNombreReg.setEnabled(true);
        IngresoApellidoReg.setEnabled(true);
        IngresoEmailReg.setEnabled(true);
        IngresoUsuarioReg.setEnabled(true);
        IngresoContrasenaReg.setEnabled(true);
    }//GEN-LAST:event_RadioRegistrarUsuActionPerformed

    private void EliminarPelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarPelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarPelActionPerformed

    private void RadioBusUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioBusUsuarioActionPerformed
        RadioPelBus.setSelected(false);
        RadioSerBus.setSelected(false);
    }//GEN-LAST:event_RadioBusUsuarioActionPerformed

    private void RadioSerBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioSerBusActionPerformed
        RadioBusUsuario.setSelected(false);
        RadioPelBus.setSelected(false);
    }//GEN-LAST:event_RadioSerBusActionPerformed

    private void RadioPelBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioPelBusActionPerformed
        RadioBusUsuario.setSelected(false);
        RadioSerBus.setSelected(false);
    }//GEN-LAST:event_RadioPelBusActionPerformed

    private void IngresoUsuarioRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresoUsuarioRegActionPerformed
        
      
    }//GEN-LAST:event_IngresoUsuarioRegActionPerformed

    private void IngresoUsuarioRegKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IngresoUsuarioRegKeyPressed
        
    }//GEN-LAST:event_IngresoUsuarioRegKeyPressed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed

    }//GEN-LAST:event_jbBuscarActionPerformed

    private void BuscarSeriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarSeriesActionPerformed
        
        String titulo = IngresoTituloSerReg.getText();
        try {
            Serie optionalSerie = repositorioSerie.findByTitulo(titulo);
            String BuscarTitulo = optionalSerie.getTitulo();
            if (BuscarTitulo.equals(titulo)) {
                JOptionPane.showMessageDialog(null, "Serie disponible: " + BuscarTitulo
                        + " consta de " + optionalSerie.getEpisodios() + " episodios en "
                        + optionalSerie.getTemporadas() + " temporadas");
                IngresoEpisodiosSerReg.setText(optionalSerie.getEpisodios().toString());
                IngresoTemporadasSerReg.setText(optionalSerie.getTemporadas().toString());
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "La serie no fue encontrada");
            IngresoTituloSerReg.setText("");
            IngresoEpisodiosSerReg.setText("");
            IngresoTemporadasSerReg.setText("");
        }
        
    }//GEN-LAST:event_BuscarSeriesActionPerformed

    private void ActualizarSeriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarSeriesActionPerformed
        
        String titulo = IngresoTituloSerReg.getText();
        Long temporadas = Long.parseLong(IngresoTemporadasSerReg.getText());
        Long episodios = Long.parseLong(IngresoEpisodiosSerReg.getText());
        try {
            Serie optionalSerie = repositorioSerie.findByTitulo(titulo);
            String BuscarTitulo = optionalSerie.getTitulo();
          if (BuscarTitulo.equals(titulo)) {
              Serie serie = repositorioSerie.findByTitulo(titulo);
              serie.setTemporadas(temporadas);
              serie.setEpisodios(episodios);
              serie = repositorioSerie.save(serie);
              JOptionPane.showMessageDialog(null, "La serie \"" + titulo +"\" ha sido actualizada con éxito.");
              IngresoTituloSerReg.setText("");
              IngresoTemporadasSerReg.setText("");
              IngresoEpisodiosSerReg.setText("");              
          } 
        }
            
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Los cambios no fueron guardados");
        }
        
    }//GEN-LAST:event_ActualizarSeriesActionPerformed

    private void BuscarSeries1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarSeries1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarSeries1ActionPerformed

    private void RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarActionPerformed
        
        String titulo = IngresoTituloSerReg.getText();
        // try {
            Serie optionalSerie = repositorioSerie.findByTitulo(titulo);
            String BuscarTitulo = optionalSerie.getTitulo();
            if (!BuscarTitulo.equals(titulo)) {
                int id_serie = (int)repositorioSerie.count() + 1;
                Serie newSerie = new Serie();
                newSerie.setId(id_serie);
                newSerie.setTitulo(IngresoTituloSerReg.getText());
                newSerie.setTemporadas(Long.parseLong(IngresoTemporadasSerReg.getText()));
                newSerie.setEpisodios(Long.parseLong(IngresoEpisodiosSerReg.getText()));
                repositorioSerie.save(newSerie);
                JOptionPane.showMessageDialog(null, "La serie \"" + IngresoTituloSerReg + "\" ha sido registrada.");
                IngresoEpisodiosSerReg.setText("");
                IngresoTemporadasSerReg.setText("");                                
            }           
            
        /*} catch (Exception e) {            
            JOptionPane.showMessageDialog(null, "La serie ya existe.");           
            IngresoTituloSerReg.setText("");
        }*/
    }//GEN-LAST:event_RegistrarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        
        String titulo = IngresoTituloSerReg.getText();
        try {
            Serie optionalSerie = repositorioSerie.findByTitulo(titulo);
            String BuscarTitulo = optionalSerie.getTitulo();
            if (BuscarTitulo.equals(titulo)) {
                int id_serie = optionalSerie.getId();
                repositorioSerie.deleteById(id_serie);
                JOptionPane.showMessageDialog(null, "La serie \"" + titulo + "\" ha sido eliminada exitosamente.");
                IngresoTituloSerReg.setText("");
                IngresoEpisodiosSerReg.setText("");
                IngresoTemporadasSerReg.setText("");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "La serie no fue encontrada");
            IngresoTituloSerReg.setText("");
        }
    }//GEN-LAST:event_EliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RedflixForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RedflixForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RedflixForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RedflixForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame frame = new JFrame("App");
                frame.setContentPane(new RedflixForm().RedflixPanel);
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.pack();
                new RedflixForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JButton AceptarPeliculas;
    private javax.swing.JButton ActualizarSeries;
    private javax.swing.JButton AgregarPelicula;
    private javax.swing.JButton AgregarSerie;
    private javax.swing.JButton AgregarUsuario;
    private javax.swing.JButton Buscar;
    private javax.swing.JButton BuscarSeries;
    private javax.swing.JButton BuscarSeries1;
    private javax.swing.JButton Busqueda;
    private javax.swing.JPanel BusquedaInterface;
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton CancelarBusqueda;
    private javax.swing.JButton CancelarPeliculas;
    private javax.swing.JButton Eliminar;
    private javax.swing.JRadioButton EliminarPel;
    private javax.swing.ButtonGroup GrupoBotonesUsuario;
    private javax.swing.JLabel Imagen;
    private javax.swing.JTextField IngresoApellidoReg;
    private javax.swing.JTextField IngresoBusqueda;
    private javax.swing.JPasswordField IngresoContrasenaReg;
    private javax.swing.JTextField IngresoDirectorPelReg;
    private javax.swing.JTextField IngresoEmailReg;
    private javax.swing.JTextField IngresoEpisodiosSerReg;
    private javax.swing.JTextField IngresoFechaPelReg;
    private javax.swing.JTextField IngresoNombreReg;
    private javax.swing.JTextField IngresoResumenPelReg;
    private javax.swing.JTextField IngresoTemporadasSerReg;
    private javax.swing.JTextField IngresoTituloPelReg;
    private javax.swing.JTextField IngresoTituloSerReg;
    private javax.swing.JTextField IngresoUsuarioReg;
    private javax.swing.JPanel Inicio;
    private javax.swing.JLabel Intro;
    private javax.swing.JLabel LabelApellidoReg;
    private javax.swing.JLabel LabelBusqueda;
    private javax.swing.JLabel LabelContrasena;
    private javax.swing.JLabel LabelDirectorPelReg;
    private javax.swing.JLabel LabelEmailReg;
    private javax.swing.JLabel LabelEpisodiosSerReg;
    private javax.swing.JLabel LabelFechaPelReg;
    private javax.swing.JLabel LabelNombreReg;
    private javax.swing.JLabel LabelResumenPelReg;
    private javax.swing.JLabel LabelTemporadaSerReg;
    private javax.swing.JLabel LabelTituloPelReg;
    private javax.swing.JLabel LabelTituloSerReg;
    private javax.swing.JLabel LabelUsuarioReg;
    private javax.swing.JPanel PeliculasInterface;
    private javax.swing.JRadioButton RadioActualizarPel;
    private javax.swing.JRadioButton RadioActualizarUsu;
    private javax.swing.JRadioButton RadioBusUsuario;
    private javax.swing.JRadioButton RadioPelBus;
    private javax.swing.JRadioButton RadioRegistrarPel;
    private javax.swing.JRadioButton RadioRegistrarUsu;
    private javax.swing.JRadioButton RadioSerBus;
    private javax.swing.JTabbedPane RedflixPanel;
    private javax.swing.JButton Registrar;
    private javax.swing.JPanel RegistroPeliculas;
    private javax.swing.JPanel RegistroSeries;
    private javax.swing.JPanel RegistroUsuarios;
    private javax.swing.JPanel SeriesInterface;
    private javax.swing.JPanel UsuariosInterface;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JLabel jlEpisodios;
    private javax.swing.JLabel jlNotificacion;
    private javax.swing.JLabel jlTemporadas;
    private javax.swing.JLabel jltitulo;
    private javax.swing.JTextField jtID;
    // End of variables declaration//GEN-END:variables

   
}
