/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.unal.Reto5.vista;


import co.edu.unal.Reto5.Reto5Application;
import co.edu.unal.Reto5.SpringContext;
import co.edu.unal.Reto5.modelos.Pelicula;
import co.edu.unal.Reto5.modelos.Serie;
import co.edu.unal.Reto5.modelos.Usuario;
import co.edu.unal.Reto5.repositorios.RepositorioPelicula;
import co.edu.unal.Reto5.repositorios.RepositorioSerie;
import co.edu.unal.Reto5.repositorios.RepositorioUsuario;

import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author Felipe
 */
public class RedflixForm extends javax.swing.JFrame {

    RepositorioSerie repositorioSerie;
    RepositorioPelicula repositorioPelicula;
    RepositorioUsuario repositorioUsuario;
    
    

    public RedflixForm() {
        initComponents();
        String[] args = {};
        Reto5Application.runSpringServer(args);
        repositorioSerie = SpringContext.getBean(RepositorioSerie.class);
        repositorioPelicula = SpringContext.getBean(RepositorioPelicula.class);
        repositorioUsuario = SpringContext.getBean(RepositorioUsuario.class);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BuscarSeries1 = new javax.swing.JButton();
        RedflixPanel = new javax.swing.JTabbedPane();
        Inicio = new javax.swing.JPanel();
        Intro = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        AgregarSerie = new javax.swing.JButton();
        AgregarPelicula = new javax.swing.JButton();
        Imagen = new javax.swing.JLabel();
        IraUsuarios = new javax.swing.JButton();
        SeriesInterface = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        BuscarSeries = new javax.swing.JButton();
        ActualizarSeries = new javax.swing.JButton();
        RegistrarSeries = new javax.swing.JButton();
        EliminarSeries = new javax.swing.JButton();
        InicioSerie = new javax.swing.JButton();
        RegistroSeries = new javax.swing.JPanel();
        LabelTituloSerReg = new javax.swing.JLabel();
        IngresoTituloSerReg = new javax.swing.JTextField();
        LabelEpisodiosSerReg = new javax.swing.JLabel();
        IngresoEpisodiosSerReg = new javax.swing.JTextField();
        LabelTemporadaSerReg = new javax.swing.JLabel();
        IngresoTemporadasSerReg = new javax.swing.JTextField();
        PeliculasInterface = new javax.swing.JPanel();
        RegistroPeliculas = new javax.swing.JPanel();
        LabelTituloPelReg = new javax.swing.JLabel();
        IngresoTituloPelReg = new javax.swing.JTextField();
        LabelResumenPelReg = new javax.swing.JLabel();
        LabelFechaPelReg = new javax.swing.JLabel();
        LabelDirectorPelReg = new javax.swing.JLabel();
        IngresoFechaPelReg = new javax.swing.JTextField();
        IngresoDirectorPelReg = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        IngresoResumenPelReg = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        BuscarPelículas = new javax.swing.JButton();
        ActualizarPeliculas = new javax.swing.JButton();
        RegistrarPeliculas = new javax.swing.JButton();
        EliminarPeliculas = new javax.swing.JButton();
        InicioPelicula = new javax.swing.JButton();
        UsuarioInterface = new javax.swing.JPanel();
        RegistroUsuario = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        IngresoUsuarioEmail = new javax.swing.JTextField();
        IngresoUserName = new javax.swing.JTextField();
        IngresoUsuarioApellido = new javax.swing.JTextField();
        IngresoUsuarioNombres = new javax.swing.JTextField();
        IngresoUsuarioPass = new javax.swing.JPasswordField();
        BuscarUsuario = new javax.swing.JButton();
        ActualizarUsuario = new javax.swing.JButton();
        RegistrarUsuario = new javax.swing.JButton();
        EliminarUsuario = new javax.swing.JButton();
        VolverInicioUsuario = new javax.swing.JButton();

        BuscarSeries1.setText("Buscar");
        BuscarSeries1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarSeries1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Redflix");
        setMinimumSize(new java.awt.Dimension(400, 400));

        RedflixPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de búsqueda"));

        Intro.setText("Bienvenido a la aplicación de redflixApp, lo mejor en streaming.");

        jLabel1.setText("Por favor seleccione la opción que desea usar:");

        AgregarSerie.setText("Serie");
        AgregarSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarSerieActionPerformed(evt);
            }
        });

        AgregarPelicula.setText("Película");
        AgregarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarPeliculaActionPerformed(evt);
            }
        });

        Imagen.setText(null);
        Imagen.setMaximumSize(new java.awt.Dimension(100, 100));
        Imagen.setMinimumSize(new java.awt.Dimension(50, 50));

        IraUsuarios.setText("Usuarios");
        IraUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IraUsuariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InicioLayout = new javax.swing.GroupLayout(Inicio);
        Inicio.setLayout(InicioLayout);
        InicioLayout.setHorizontalGroup(
            InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Intro)
                    .addComponent(jLabel1)
                    .addGroup(InicioLayout.createSequentialGroup()
                        .addComponent(AgregarSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AgregarPelicula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IraUsuarios))
                    .addComponent(Imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        InicioLayout.setVerticalGroup(
            InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicioLayout.createSequentialGroup()
                .addComponent(Intro)
                .addGap(18, 18, 18)
                .addComponent(Imagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgregarPelicula)
                    .addComponent(AgregarSerie)
                    .addComponent(IraUsuarios))
                .addContainerGap(284, Short.MAX_VALUE))
        );

        RedflixPanel.addTab("Inicio", Inicio);

        BuscarSeries.setText("Buscar");
        BuscarSeries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarSeriesActionPerformed(evt);
            }
        });

        ActualizarSeries.setText("Actualizar");
        ActualizarSeries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarSeriesActionPerformed(evt);
            }
        });

        RegistrarSeries.setText("Registrar");
        RegistrarSeries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarSeriesActionPerformed(evt);
            }
        });

        EliminarSeries.setText("Eliminar");
        EliminarSeries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarSeriesActionPerformed(evt);
            }
        });

        InicioSerie.setText("Volver a Inicio");
        InicioSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioSerieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(BuscarSeries)
                        .addGap(18, 18, 18)
                        .addComponent(ActualizarSeries)
                        .addGap(18, 18, 18)
                        .addComponent(RegistrarSeries)
                        .addGap(18, 18, 18)
                        .addComponent(EliminarSeries))
                    .addComponent(InicioSerie))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EliminarSeries)
                    .addComponent(RegistrarSeries)
                    .addComponent(ActualizarSeries)
                    .addComponent(BuscarSeries))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InicioSerie)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        RegistroSeries.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro/Actualización"));
        RegistroSeries.setName("Registro/Actualización"); // NOI18N
        RegistroSeries.setPreferredSize(new java.awt.Dimension(182, 200));

        LabelTituloSerReg.setText("Título:");

        IngresoTituloSerReg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IngresoTituloSerRegKeyTyped(evt);
            }
        });

        LabelEpisodiosSerReg.setText("Episodios:");

        IngresoEpisodiosSerReg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IngresoEpisodiosSerRegKeyTyped(evt);
            }
        });

        LabelTemporadaSerReg.setText("Temporadas:");

        IngresoTemporadasSerReg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IngresoTemporadasSerRegKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout RegistroSeriesLayout = new javax.swing.GroupLayout(RegistroSeries);
        RegistroSeries.setLayout(RegistroSeriesLayout);
        RegistroSeriesLayout.setHorizontalGroup(
            RegistroSeriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroSeriesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RegistroSeriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistroSeriesLayout.createSequentialGroup()
                        .addGroup(RegistroSeriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelTemporadaSerReg)
                            .addComponent(LabelTituloSerReg)
                            .addComponent(LabelEpisodiosSerReg))
                        .addGap(0, 305, Short.MAX_VALUE))
                    .addComponent(IngresoTemporadasSerReg)
                    .addComponent(IngresoEpisodiosSerReg)
                    .addComponent(IngresoTituloSerReg))
                .addContainerGap())
        );
        RegistroSeriesLayout.setVerticalGroup(
            RegistroSeriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroSeriesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelTituloSerReg)
                .addGap(1, 1, 1)
                .addComponent(IngresoTituloSerReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelEpisodiosSerReg)
                .addGap(4, 4, 4)
                .addComponent(IngresoEpisodiosSerReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelTemporadaSerReg)
                .addGap(3, 3, 3)
                .addComponent(IngresoTemporadasSerReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout SeriesInterfaceLayout = new javax.swing.GroupLayout(SeriesInterface);
        SeriesInterface.setLayout(SeriesInterfaceLayout);
        SeriesInterfaceLayout.setHorizontalGroup(
            SeriesInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SeriesInterfaceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SeriesInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegistroSeries, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        SeriesInterfaceLayout.setVerticalGroup(
            SeriesInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SeriesInterfaceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RegistroSeries, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 139, Short.MAX_VALUE))
        );

        RedflixPanel.addTab("Series", SeriesInterface);

        RegistroPeliculas.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro"));
        RegistroPeliculas.setName("Registro/Actualización"); // NOI18N
        RegistroPeliculas.setPreferredSize(new java.awt.Dimension(182, 200));

        LabelTituloPelReg.setText("Título:");

        IngresoTituloPelReg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IngresoTituloPelRegKeyTyped(evt);
            }
        });

        LabelResumenPelReg.setText("Resumen:");

        LabelFechaPelReg.setText("Fecha de lanzamiento:");

        LabelDirectorPelReg.setText("Director:");

        IngresoFechaPelReg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IngresoFechaPelRegKeyTyped(evt);
            }
        });

        IngresoResumenPelReg.setColumns(20);
        IngresoResumenPelReg.setLineWrap(true);
        IngresoResumenPelReg.setRows(5);
        jScrollPane1.setViewportView(IngresoResumenPelReg);

        javax.swing.GroupLayout RegistroPeliculasLayout = new javax.swing.GroupLayout(RegistroPeliculas);
        RegistroPeliculas.setLayout(RegistroPeliculasLayout);
        RegistroPeliculasLayout.setHorizontalGroup(
            RegistroPeliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroPeliculasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RegistroPeliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IngresoFechaPelReg)
                    .addComponent(IngresoDirectorPelReg, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                    .addComponent(IngresoTituloPelReg)
                    .addGroup(RegistroPeliculasLayout.createSequentialGroup()
                        .addGroup(RegistroPeliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelDirectorPelReg)
                            .addComponent(LabelTituloPelReg)
                            .addComponent(LabelResumenPelReg)
                            .addComponent(LabelFechaPelReg))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        RegistroPeliculasLayout.setVerticalGroup(
            RegistroPeliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroPeliculasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelTituloPelReg)
                .addGap(1, 1, 1)
                .addComponent(IngresoTituloPelReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelResumenPelReg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                .addGap(4, 4, 4)
                .addComponent(LabelFechaPelReg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IngresoFechaPelReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelDirectorPelReg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IngresoDirectorPelReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        BuscarPelículas.setText("Buscar");
        BuscarPelículas.setToolTipText("");
        BuscarPelículas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarPelículasActionPerformed(evt);
            }
        });

        ActualizarPeliculas.setText("Actualizar");
        ActualizarPeliculas.setToolTipText("");
        ActualizarPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarPeliculasActionPerformed(evt);
            }
        });

        RegistrarPeliculas.setText("Registrar");
        RegistrarPeliculas.setToolTipText("");
        RegistrarPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarPeliculasActionPerformed(evt);
            }
        });

        EliminarPeliculas.setText("Eliminar");
        EliminarPeliculas.setToolTipText("");
        EliminarPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarPeliculasActionPerformed(evt);
            }
        });

        InicioPelicula.setText("Volver a Inicio");
        InicioPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioPeliculaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(BuscarPelículas)
                        .addGap(19, 19, 19)
                        .addComponent(ActualizarPeliculas)
                        .addGap(18, 18, 18)
                        .addComponent(RegistrarPeliculas)
                        .addGap(18, 18, 18)
                        .addComponent(EliminarPeliculas))
                    .addComponent(InicioPelicula))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ActualizarPeliculas)
                    .addComponent(RegistrarPeliculas)
                    .addComponent(EliminarPeliculas)
                    .addComponent(BuscarPelículas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InicioPelicula)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PeliculasInterfaceLayout = new javax.swing.GroupLayout(PeliculasInterface);
        PeliculasInterface.setLayout(PeliculasInterfaceLayout);
        PeliculasInterfaceLayout.setHorizontalGroup(
            PeliculasInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PeliculasInterfaceLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(PeliculasInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegistroPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PeliculasInterfaceLayout.setVerticalGroup(
            PeliculasInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PeliculasInterfaceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RegistroPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        RedflixPanel.addTab("Películas", PeliculasInterface);

        RegistroUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro"));

        jLabel2.setText("Username:");

        jLabel3.setText("Correo Electrónico:");

        jLabel4.setText("Nombres: ");

        jLabel5.setText("Apellidos:");

        jLabel6.setText("Contraseña:");

        javax.swing.GroupLayout RegistroUsuarioLayout = new javax.swing.GroupLayout(RegistroUsuario);
        RegistroUsuario.setLayout(RegistroUsuarioLayout);
        RegistroUsuarioLayout.setHorizontalGroup(
            RegistroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RegistroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IngresoUsuarioApellido)
                    .addGroup(RegistroUsuarioLayout.createSequentialGroup()
                        .addGroup(RegistroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(0, 277, Short.MAX_VALUE))
                    .addComponent(IngresoUsuarioNombres)
                    .addComponent(IngresoUsuarioEmail)
                    .addComponent(IngresoUsuarioPass)
                    .addComponent(IngresoUserName))
                .addContainerGap())
        );
        RegistroUsuarioLayout.setVerticalGroup(
            RegistroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IngresoUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IngresoUsuarioPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IngresoUsuarioEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IngresoUsuarioNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IngresoUsuarioApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BuscarUsuario.setText("Buscar");
        BuscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarUsuarioActionPerformed(evt);
            }
        });

        ActualizarUsuario.setText("Actualizar");
        ActualizarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarUsuarioActionPerformed(evt);
            }
        });

        RegistrarUsuario.setText("Registrar");
        RegistrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarUsuarioActionPerformed(evt);
            }
        });

        EliminarUsuario.setText("Eliminar");
        EliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarUsuarioActionPerformed(evt);
            }
        });

        VolverInicioUsuario.setText("Volver a Inicio");
        VolverInicioUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverInicioUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UsuarioInterfaceLayout = new javax.swing.GroupLayout(UsuarioInterface);
        UsuarioInterface.setLayout(UsuarioInterfaceLayout);
        UsuarioInterfaceLayout.setHorizontalGroup(
            UsuarioInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UsuarioInterfaceLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RegistroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(UsuarioInterfaceLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(UsuarioInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VolverInicioUsuario)
                    .addGroup(UsuarioInterfaceLayout.createSequentialGroup()
                        .addComponent(BuscarUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(ActualizarUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(RegistrarUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(EliminarUsuario)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        UsuarioInterfaceLayout.setVerticalGroup(
            UsuarioInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsuarioInterfaceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RegistroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UsuarioInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BuscarUsuario)
                    .addComponent(ActualizarUsuario)
                    .addComponent(EliminarUsuario)
                    .addComponent(RegistrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VolverInicioUsuario)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        RegistroUsuario.getAccessibleContext().setAccessibleName("Registro");

        RedflixPanel.addTab("Usuarios", UsuarioInterface);
        UsuarioInterface.getAccessibleContext().setAccessibleName("UsuarioInterface");
        UsuarioInterface.getAccessibleContext().setAccessibleParent(Inicio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RedflixPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RedflixPanel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarSeries1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarSeries1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarSeries1ActionPerformed

    private void EliminarPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarPeliculasActionPerformed
        String titulo_pel = IngresoTituloPelReg.getText();
        try {
            Pelicula optionalPelicula = repositorioPelicula.findByTitulo(titulo_pel);
            String BuscarTitulo = optionalPelicula.getTitulo();
            if (BuscarTitulo.equals(titulo_pel)) {
                int id_serie = optionalPelicula.getId_pelicula();
                repositorioPelicula.deleteById(id_serie);
                JOptionPane.showMessageDialog(null, "Se eliminó exitosamente la película: \"" + titulo_pel + "\" ");
                IngresoTituloPelReg.setText("");
                IngresoDirectorPelReg.setText("");
                IngresoFechaPelReg.setText("");
                IngresoResumenPelReg.setText("");

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "La película no fue encontrada");
            IngresoTituloSerReg.setText("");
        }
    }//GEN-LAST:event_EliminarPeliculasActionPerformed

    private void ActualizarPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarPeliculasActionPerformed
        String titulo_pel = IngresoTituloPelReg.getText();
        try {
            Pelicula optionalPelicula = repositorioPelicula.findByTitulo(titulo_pel);
            String BuscarTitulo = optionalPelicula.getTitulo();
            if (BuscarTitulo.equals(titulo_pel)) {
                Pelicula pelicula = repositorioPelicula.findByTitulo(titulo_pel);
                pelicula.setResumen(IngresoResumenPelReg.getText());
                pelicula.setAnio(IngresoFechaPelReg.getText());
                pelicula.setDirector(IngresoDirectorPelReg.getText());
                pelicula = repositorioPelicula.save(pelicula);
                JOptionPane.showMessageDialog(null, "La película \"" + titulo_pel +"\" ha sido actualizada con éxito.");
                IngresoTituloPelReg.setText("");
                IngresoResumenPelReg.setText("");
                IngresoFechaPelReg.setText("");
                IngresoDirectorPelReg.setText("");
            }
        }

        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Los cambios no fueron guardados");
        }
    }//GEN-LAST:event_ActualizarPeliculasActionPerformed

    private void RegistrarPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarPeliculasActionPerformed
        String titulo_pel = IngresoTituloPelReg.getText();
        Pelicula optionalPelicula = repositorioPelicula.findByTitulo(titulo_pel);
        if (optionalPelicula == null){
            Pelicula newPelicula = new Pelicula();
            newPelicula.setTitulo(IngresoTituloPelReg.getText());
            newPelicula.setResumen(IngresoResumenPelReg.getText());
            newPelicula.setAnio(IngresoFechaPelReg.getText());
            newPelicula.setDirector(IngresoDirectorPelReg.getText());

            repositorioPelicula.save(newPelicula);
            JOptionPane.showMessageDialog(null, "Se registró correctamente la película: \"" + titulo_pel + "\"");
            IngresoTituloPelReg.setText("");
            IngresoResumenPelReg.setText("");
            IngresoFechaPelReg.setText("");
            IngresoDirectorPelReg.setText("");
        }else {
            JOptionPane.showMessageDialog(null, "La pelicula ya existe.");
            IngresoTituloSerReg.setText("");
        }
    }//GEN-LAST:event_RegistrarPeliculasActionPerformed

    private void BuscarPelículasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarPelículasActionPerformed
        String titulo = IngresoTituloPelReg.getText();
        try {
            Pelicula optionalPelicula = repositorioPelicula.findByTitulo(titulo);
            String BuscarTitulo = optionalPelicula.getTitulo();
            if (BuscarTitulo.equals(titulo)) {
                JOptionPane.showMessageDialog(null, "Película disponible: " + BuscarTitulo
                    + " fue lanzada en " + optionalPelicula.getAnio()+ " por el director "
                    + optionalPelicula.getDirector());

                IngresoTituloPelReg.setText(optionalPelicula.getTitulo());
                IngresoResumenPelReg.setText(optionalPelicula.getResumen());
                IngresoFechaPelReg.setText(optionalPelicula.getAnio());
                IngresoDirectorPelReg.setText(optionalPelicula.getDirector());
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "La película no fue encontrada");
            IngresoTituloPelReg.setText("");
            IngresoResumenPelReg.setText("");
            IngresoFechaPelReg.setText("");
            IngresoDirectorPelReg.setText("");
        }
    }//GEN-LAST:event_BuscarPelículasActionPerformed

    private void AgregarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarPeliculaActionPerformed
        RedflixPanel.setSelectedIndex(2);
    }//GEN-LAST:event_AgregarPeliculaActionPerformed

    private void AgregarSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarSerieActionPerformed
        RedflixPanel.setSelectedIndex(1);
    }//GEN-LAST:event_AgregarSerieActionPerformed

    private void EliminarSeriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarSeriesActionPerformed

        String titulo = IngresoTituloSerReg.getText();
        try {
            Serie optionalSerie = repositorioSerie.findByTitulo(titulo);
            String BuscarTitulo = optionalSerie.getTitulo();
            if (BuscarTitulo.equals(titulo)) {
                int id_serie = optionalSerie.getId();
                repositorioSerie.deleteById(id_serie);
                JOptionPane.showMessageDialog(null, "La serie \"" + titulo + "\" ha sido eliminada exitosamente.");
                IngresoTituloSerReg.setText("");
                IngresoEpisodiosSerReg.setText("");
                IngresoTemporadasSerReg.setText("");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "La serie no fue encontrada");
            IngresoTituloSerReg.setText("");
        }
    }//GEN-LAST:event_EliminarSeriesActionPerformed

    private void RegistrarSeriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarSeriesActionPerformed

        String titulo = IngresoTituloSerReg.getText();
        Serie optionalSerie = repositorioSerie.findByTitulo(titulo);
        if (optionalSerie == null){
            Serie newSerie = new Serie();
            newSerie.setTitulo(IngresoTituloSerReg.getText());
            newSerie.setTemporadas(Long.parseLong(IngresoTemporadasSerReg.getText()));
            newSerie.setEpisodios(Long.parseLong(IngresoEpisodiosSerReg.getText()));
            repositorioSerie.save(newSerie);
            JOptionPane.showMessageDialog(null, "Se registró correctamente la serie: \"" + titulo + "\"");
            IngresoTituloSerReg.setText("");
            IngresoEpisodiosSerReg.setText("");
            IngresoTemporadasSerReg.setText("");
        }else {
            JOptionPane.showMessageDialog(null, "La serie ya existe.");
            IngresoTituloSerReg.setText("");
        }
    }//GEN-LAST:event_RegistrarSeriesActionPerformed

    private void ActualizarSeriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarSeriesActionPerformed

        String titulo = IngresoTituloSerReg.getText();
        Long temporadas = Long.parseLong(IngresoTemporadasSerReg.getText());
        Long episodios = Long.parseLong(IngresoEpisodiosSerReg.getText());
        try {
            Serie optionalSerie = repositorioSerie.findByTitulo(titulo);
            String BuscarTitulo = optionalSerie.getTitulo();
            if (BuscarTitulo.equals(titulo)) {
                Serie serie = repositorioSerie.findByTitulo(titulo);
                serie.setTemporadas(temporadas);
                serie.setEpisodios(episodios);
                serie = repositorioSerie.save(serie);
                JOptionPane.showMessageDialog(null, "La serie \"" + titulo +"\" ha sido actualizada con éxito.");
                IngresoTituloSerReg.setText("");
                IngresoTemporadasSerReg.setText("");
                IngresoEpisodiosSerReg.setText("");
            }
        }

        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Los cambios no fueron guardados");
        }
    }//GEN-LAST:event_ActualizarSeriesActionPerformed

    private void BuscarSeriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarSeriesActionPerformed

        String titulo = IngresoTituloSerReg.getText();
        try {
            Serie optionalSerie = repositorioSerie.findByTitulo(titulo);
            String BuscarTitulo = optionalSerie.getTitulo();
            if (BuscarTitulo.equals(titulo)) {
                JOptionPane.showMessageDialog(null, "Serie disponible: " + BuscarTitulo
                    + " consta de " + optionalSerie.getEpisodios() + " episodios en "
                    + optionalSerie.getTemporadas() + " temporadas");
                IngresoEpisodiosSerReg.setText(optionalSerie.getEpisodios().toString());
                IngresoTemporadasSerReg.setText(optionalSerie.getTemporadas().toString());
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "La serie que busca no fue encontrada");
            IngresoTituloSerReg.setText("");
            IngresoEpisodiosSerReg.setText("");
            IngresoTemporadasSerReg.setText("");
        }
    }//GEN-LAST:event_BuscarSeriesActionPerformed

    private void InicioSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioSerieActionPerformed
        RedflixPanel.setSelectedIndex(0);
    }//GEN-LAST:event_InicioSerieActionPerformed

    private void InicioPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioPeliculaActionPerformed
        RedflixPanel.setSelectedIndex(0);
    }//GEN-LAST:event_InicioPeliculaActionPerformed

    private void IngresoEpisodiosSerRegKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IngresoEpisodiosSerRegKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Digite solo números");
        }
    }//GEN-LAST:event_IngresoEpisodiosSerRegKeyTyped

    private void IngresoTemporadasSerRegKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IngresoTemporadasSerRegKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Digite solo números");
        }
    }//GEN-LAST:event_IngresoTemporadasSerRegKeyTyped

    private void IngresoTituloSerRegKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IngresoTituloSerRegKeyTyped
        if(IngresoTituloSerReg.getText().length() >= 45){
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_IngresoTituloSerRegKeyTyped

    private void IngresoFechaPelRegKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IngresoFechaPelRegKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Digite solo números");
        }
    }//GEN-LAST:event_IngresoFechaPelRegKeyTyped

    private void IngresoTituloPelRegKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IngresoTituloPelRegKeyTyped
        if(IngresoTituloSerReg.getText().length() >= 45){
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_IngresoTituloPelRegKeyTyped

    private void VolverInicioUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverInicioUsuarioActionPerformed
       RedflixPanel.setSelectedIndex(0);
    }//GEN-LAST:event_VolverInicioUsuarioActionPerformed

    private void IraUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IraUsuariosActionPerformed
        RedflixPanel.setSelectedIndex(3);
    }//GEN-LAST:event_IraUsuariosActionPerformed

    private void BuscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarUsuarioActionPerformed
        String user_id = IngresoUserName.getText();
        try {
            Usuario optionalUsuario = repositorioUsuario.findByUserName(user_id);
            String BuscarUsuario = optionalUsuario.getUserName();
            if (BuscarUsuario.equals(user_id)) {
                JOptionPane.showMessageDialog(null, "El usuario se encuentra registrado: " + BuscarUsuario
                    + ", Nombre: " + optionalUsuario.getNombre_user()+ ", Apellidos: "
                    + optionalUsuario.getApellido_user());

                IngresoUserName.setText(optionalUsuario.getUserName());
                IngresoUsuarioNombres.setText(optionalUsuario.getNombre_user());
                IngresoUsuarioApellido.setText(optionalUsuario.getApellido_user());
                IngresoUsuarioEmail.setText(optionalUsuario.getEmail());
                IngresoUsuarioPass.setText(optionalUsuario.getContrasenia());
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "El usuario no se encuentra registrado");
            IngresoUserName.setText("");
            IngresoUsuarioNombres.setText("");
            IngresoUsuarioApellido.setText("");
            IngresoUsuarioEmail.setText("");
            IngresoUsuarioPass.setText("");
        }
    }//GEN-LAST:event_BuscarUsuarioActionPerformed

    private void ActualizarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarUsuarioActionPerformed
        String user_id = IngresoUserName.getText();
        try {
            Usuario optionalUsuario = repositorioUsuario.findByUserName(user_id);
            String BuscarUsuario = optionalUsuario.getUserName();
            if (BuscarUsuario.equals(user_id)) {
                Usuario usuario = repositorioUsuario.findByUserName(user_id);
                usuario.setUserName(IngresoUserName.getText());
                usuario.setNombre_user(IngresoUsuarioNombres.getText());
                usuario.setApellido_user(IngresoUsuarioApellido.getText());
                usuario.setEmail(IngresoUsuarioEmail.getText());
                usuario.setContrasenia(IngresoUsuarioPass.getText());
                usuario = repositorioUsuario.save(usuario);
                JOptionPane.showMessageDialog(null, "El usuario \"" + user_id +"\" ha sido actualizado con éxito.");
                IngresoUserName.setText("");
                IngresoUsuarioNombres.setText("");
                IngresoUsuarioApellido.setText("");
                IngresoUsuarioEmail.setText("");
                IngresoUsuarioPass.setText("");
            }
        }

        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Los cambios no fueron guardados");
            IngresoUserName.setText("");
            IngresoUsuarioNombres.setText("");
            IngresoUsuarioApellido.setText("");
            IngresoUsuarioEmail.setText("");
            IngresoUsuarioPass.setText("");
        }
    }//GEN-LAST:event_ActualizarUsuarioActionPerformed

    private void EliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarUsuarioActionPerformed
       String user_id = IngresoUserName.getText();
        try {
            Usuario optionalUsuario = repositorioUsuario.findByUserName(user_id);
            String BuscarUsuario = optionalUsuario.getUserName();
             if (BuscarUsuario.equals(user_id)) {
                repositorioUsuario.delete(optionalUsuario);
                JOptionPane.showMessageDialog(null, "Se eliminó exitosamente el usuario: \"" + user_id + "\" ");
                IngresoUserName.setText("");
                IngresoUsuarioNombres.setText("");
                IngresoUsuarioApellido.setText("");
                IngresoUsuarioEmail.setText("");
                IngresoUsuarioPass.setText("");

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "El usuario no se encuentra registrado");
            IngresoUserName.setText("");
            IngresoUsuarioNombres.setText("");
            IngresoUsuarioApellido.setText("");
            IngresoUsuarioEmail.setText("");
            IngresoUsuarioPass.setText("");
        }
    }//GEN-LAST:event_EliminarUsuarioActionPerformed

    private void RegistrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarUsuarioActionPerformed
        String user_id = IngresoUserName.getText();
        Usuario optionalUsuario = repositorioUsuario.findByUserName(user_id);
        String BuscarUsuario = optionalUsuario.getUserName();
        
         if (BuscarUsuario.equals(user_id)) {
             JOptionPane.showMessageDialog(null, "El usuario ya existe");
             IngresoUserName.setText("");
             IngresoUsuarioNombres.setText("");
             IngresoUsuarioApellido.setText("");
             IngresoUsuarioEmail.setText("");
             IngresoUsuarioPass.setText("");
         }
            
         else if (optionalUsuario == null){
            Usuario newUsuario = new Usuario();
            newUsuario.setUserName(user_id);
            newUsuario.setNombre_user(IngresoUsuarioNombres.getText());
            newUsuario.setApellido_user(IngresoUsuarioApellido.getText());
            newUsuario.setEmail(IngresoUsuarioEmail.getText());
            newUsuario.setContrasenia(IngresoUsuarioPass.getText());             
            repositorioUsuario.save(newUsuario);
            JOptionPane.showMessageDialog(null, "Se registró correctamente el usuario: \"" + user_id + "\"");
            IngresoUserName.setText("");
            IngresoUsuarioNombres.setText("");
            IngresoUsuarioApellido.setText("");
            IngresoUsuarioEmail.setText("");
            IngresoUsuarioPass.setText("");
        } 
    }//GEN-LAST:event_RegistrarUsuarioActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RedflixForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RedflixForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RedflixForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RedflixForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame frame = new JFrame("App");
                frame.setContentPane(new RedflixForm().RedflixPanel);
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.pack();
                new RedflixForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarPeliculas;
    private javax.swing.JButton ActualizarSeries;
    private javax.swing.JButton ActualizarUsuario;
    private javax.swing.JButton AgregarPelicula;
    private javax.swing.JButton AgregarSerie;
    private javax.swing.JButton BuscarPelículas;
    private javax.swing.JButton BuscarSeries;
    private javax.swing.JButton BuscarSeries1;
    private javax.swing.JButton BuscarUsuario;
    private javax.swing.JButton EliminarPeliculas;
    private javax.swing.JButton EliminarSeries;
    private javax.swing.JButton EliminarUsuario;
    private javax.swing.JLabel Imagen;
    private javax.swing.JTextField IngresoDirectorPelReg;
    private javax.swing.JTextField IngresoDirectorPelReg1;
    private javax.swing.JTextField IngresoEpisodiosSerReg;
    private javax.swing.JTextField IngresoFechaPelReg;
    private javax.swing.JTextField IngresoFechaPelReg1;
    private javax.swing.JTextArea IngresoResumenPelReg;
    private javax.swing.JTextArea IngresoResumenPelReg1;
    private javax.swing.JTextField IngresoTemporadasSerReg;
    private javax.swing.JTextField IngresoTituloPelReg;
    private javax.swing.JTextField IngresoTituloPelReg1;
    private javax.swing.JTextField IngresoTituloSerReg;
    private javax.swing.JTextField IngresoUserName;
    private javax.swing.JTextField IngresoUsuarioApellido;
    private javax.swing.JTextField IngresoUsuarioEmail;
    private javax.swing.JTextField IngresoUsuarioNombres;
    private javax.swing.JPasswordField IngresoUsuarioPass;
    private javax.swing.JPanel Inicio;
    private javax.swing.JButton InicioPelicula;
    private javax.swing.JButton InicioSerie;
    private javax.swing.JLabel Intro;
    private javax.swing.JButton IraUsuarios;
    private javax.swing.JLabel LabelDirectorPelReg;
    private javax.swing.JLabel LabelDirectorPelReg1;
    private javax.swing.JLabel LabelEpisodiosSerReg;
    private javax.swing.JLabel LabelFechaPelReg;
    private javax.swing.JLabel LabelFechaPelReg1;
    private javax.swing.JLabel LabelResumenPelReg;
    private javax.swing.JLabel LabelResumenPelReg1;
    private javax.swing.JLabel LabelTemporadaSerReg;
    private javax.swing.JLabel LabelTituloPelReg;
    private javax.swing.JLabel LabelTituloPelReg1;
    private javax.swing.JLabel LabelTituloSerReg;
    private javax.swing.JPanel PeliculasInterface;
    private javax.swing.JTabbedPane RedflixPanel;
    private javax.swing.JButton RegistrarPeliculas;
    private javax.swing.JButton RegistrarSeries;
    private javax.swing.JButton RegistrarUsuario;
    private javax.swing.JPanel RegistroPeliculas;
    private javax.swing.JPanel RegistroPeliculas1;
    private javax.swing.JPanel RegistroSeries;
    private javax.swing.JPanel RegistroUsuario;
    private javax.swing.JPanel SeriesInterface;
    private javax.swing.JPanel UsuarioInterface;
    private javax.swing.JButton VolverInicioUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

   
}
