/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.unal.Reto5.vista;


import co.edu.unal.Reto5.Reto5Application;
import co.edu.unal.Reto5.SpringContext;
import co.edu.unal.Reto5.modelos.Pelicula;
import co.edu.unal.Reto5.modelos.Serie;
import co.edu.unal.Reto5.repositorios.RepositorioPelicula;
import co.edu.unal.Reto5.repositorios.RepositorioSerie;
import co.edu.unal.Reto5.repositorios.RepositorioUsuario;

import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author Felipe
 */
public class RedflixForm extends javax.swing.JFrame {

    RepositorioSerie repositorioSerie;
    RepositorioPelicula repositorioPelicula;
    RepositorioUsuario repositorioUsuario;
    

    public RedflixForm() {
        initComponents();
        String[] args = {};
        Reto5Application.runSpringServer(args);
        repositorioSerie = SpringContext.getBean(RepositorioSerie.class);
        repositorioPelicula = SpringContext.getBean(RepositorioPelicula.class);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BuscarSeries1 = new javax.swing.JButton();
        RedflixPanel = new javax.swing.JTabbedPane();
        Inicio = new javax.swing.JPanel();
        Intro = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        AgregarSerie = new javax.swing.JButton();
        AgregarPelicula = new javax.swing.JButton();
        Imagen = new javax.swing.JLabel();
        SeriesInterface = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        BuscarSeries = new javax.swing.JButton();
        ActualizarSeries = new javax.swing.JButton();
        RegistrarSeries = new javax.swing.JButton();
        EliminarSeries = new javax.swing.JButton();
        InicioSerie = new javax.swing.JButton();
        RegistroSeries = new javax.swing.JPanel();
        LabelTituloSerReg = new javax.swing.JLabel();
        IngresoTituloSerReg = new javax.swing.JTextField();
        LabelEpisodiosSerReg = new javax.swing.JLabel();
        IngresoEpisodiosSerReg = new javax.swing.JTextField();
        LabelTemporadaSerReg = new javax.swing.JLabel();
        IngresoTemporadasSerReg = new javax.swing.JTextField();
        PeliculasInterface = new javax.swing.JPanel();
        RegistroPeliculas = new javax.swing.JPanel();
        LabelTituloPelReg = new javax.swing.JLabel();
        IngresoTituloPelReg = new javax.swing.JTextField();
        LabelResumenPelReg = new javax.swing.JLabel();
        LabelFechaPelReg = new javax.swing.JLabel();
        LabelDirectorPelReg = new javax.swing.JLabel();
        IngresoFechaPelReg = new javax.swing.JTextField();
        IngresoDirectorPelReg = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        IngresoResumenPelReg = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        BuscarPelículas = new javax.swing.JButton();
        ActualizarPeliculas = new javax.swing.JButton();
        RegistrarPeliculas = new javax.swing.JButton();
        EliminarPeliculas = new javax.swing.JButton();
        InicioPelicula = new javax.swing.JButton();

        BuscarSeries1.setText("Buscar");
        BuscarSeries1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarSeries1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Redflix");
        setMaximumSize(new java.awt.Dimension(500, 500));
        setMinimumSize(new java.awt.Dimension(400, 400));

        RedflixPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de búsqueda"));

        Intro.setText("Bienvenido a la aplicación de redflixApp, lo mejor en streaming.");

        jLabel1.setText("Por favor seleccione la opción que desea usar:");

        AgregarSerie.setText("Serie");
        AgregarSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarSerieActionPerformed(evt);
            }
        });

        AgregarPelicula.setText("Película");
        AgregarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarPeliculaActionPerformed(evt);
            }
        });

        Imagen.setIcon(new javax.swing.ImageIcon("E:\\Felipe\\Documents\\Git\\Reto5\\Redflix.png")); // NOI18N
        Imagen.setText(null);
        Imagen.setMaximumSize(new java.awt.Dimension(100, 100));
        Imagen.setMinimumSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout InicioLayout = new javax.swing.GroupLayout(Inicio);
        Inicio.setLayout(InicioLayout);
        InicioLayout.setHorizontalGroup(
            InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Intro)
                    .addComponent(jLabel1)
                    .addGroup(InicioLayout.createSequentialGroup()
                        .addComponent(AgregarSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AgregarPelicula))
                    .addComponent(Imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        InicioLayout.setVerticalGroup(
            InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicioLayout.createSequentialGroup()
                .addComponent(Intro)
                .addGap(18, 18, 18)
                .addComponent(Imagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgregarPelicula)
                    .addComponent(AgregarSerie))
                .addContainerGap(205, Short.MAX_VALUE))
        );

        RedflixPanel.addTab("Inicio", Inicio);

        BuscarSeries.setText("Buscar");
        BuscarSeries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarSeriesActionPerformed(evt);
            }
        });

        ActualizarSeries.setText("Actualizar");
        ActualizarSeries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarSeriesActionPerformed(evt);
            }
        });

        RegistrarSeries.setText("Registrar");
        RegistrarSeries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarSeriesActionPerformed(evt);
            }
        });

        EliminarSeries.setText("Eliminar");
        EliminarSeries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarSeriesActionPerformed(evt);
            }
        });

        InicioSerie.setText("Volver a Inicio");
        InicioSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioSerieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(BuscarSeries)
                        .addGap(18, 18, 18)
                        .addComponent(ActualizarSeries)
                        .addGap(18, 18, 18)
                        .addComponent(RegistrarSeries)
                        .addGap(18, 18, 18)
                        .addComponent(EliminarSeries))
                    .addComponent(InicioSerie))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EliminarSeries)
                    .addComponent(RegistrarSeries)
                    .addComponent(ActualizarSeries)
                    .addComponent(BuscarSeries))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InicioSerie)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        RegistroSeries.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro/Actualización"));
        RegistroSeries.setName("Registro/Actualización"); // NOI18N
        RegistroSeries.setPreferredSize(new java.awt.Dimension(182, 200));

        LabelTituloSerReg.setText("Título:");

        LabelEpisodiosSerReg.setText("Episodios:");

        LabelTemporadaSerReg.setText("Temporadas:");

        javax.swing.GroupLayout RegistroSeriesLayout = new javax.swing.GroupLayout(RegistroSeries);
        RegistroSeries.setLayout(RegistroSeriesLayout);
        RegistroSeriesLayout.setHorizontalGroup(
            RegistroSeriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroSeriesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RegistroSeriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistroSeriesLayout.createSequentialGroup()
                        .addGroup(RegistroSeriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelTemporadaSerReg)
                            .addComponent(LabelTituloSerReg)
                            .addComponent(LabelEpisodiosSerReg))
                        .addGap(0, 289, Short.MAX_VALUE))
                    .addComponent(IngresoTemporadasSerReg)
                    .addComponent(IngresoEpisodiosSerReg)
                    .addComponent(IngresoTituloSerReg))
                .addContainerGap())
        );
        RegistroSeriesLayout.setVerticalGroup(
            RegistroSeriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroSeriesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelTituloSerReg)
                .addGap(1, 1, 1)
                .addComponent(IngresoTituloSerReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelEpisodiosSerReg)
                .addGap(4, 4, 4)
                .addComponent(IngresoEpisodiosSerReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelTemporadaSerReg)
                .addGap(3, 3, 3)
                .addComponent(IngresoTemporadasSerReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout SeriesInterfaceLayout = new javax.swing.GroupLayout(SeriesInterface);
        SeriesInterface.setLayout(SeriesInterfaceLayout);
        SeriesInterfaceLayout.setHorizontalGroup(
            SeriesInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SeriesInterfaceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SeriesInterfaceLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RegistroSeries, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        SeriesInterfaceLayout.setVerticalGroup(
            SeriesInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SeriesInterfaceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RegistroSeries, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 139, Short.MAX_VALUE))
        );

        RedflixPanel.addTab("Series", SeriesInterface);

        RegistroPeliculas.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro"));
        RegistroPeliculas.setName("Registro/Actualización"); // NOI18N
        RegistroPeliculas.setPreferredSize(new java.awt.Dimension(182, 200));

        LabelTituloPelReg.setText("Título:");

        LabelResumenPelReg.setText("Resumen:");

        LabelFechaPelReg.setText("Fecha de lanzamiento:");

        LabelDirectorPelReg.setText("Director:");

        IngresoResumenPelReg.setColumns(20);
        IngresoResumenPelReg.setLineWrap(true);
        IngresoResumenPelReg.setRows(5);
        jScrollPane1.setViewportView(IngresoResumenPelReg);

        javax.swing.GroupLayout RegistroPeliculasLayout = new javax.swing.GroupLayout(RegistroPeliculas);
        RegistroPeliculas.setLayout(RegistroPeliculasLayout);
        RegistroPeliculasLayout.setHorizontalGroup(
            RegistroPeliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroPeliculasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RegistroPeliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IngresoFechaPelReg)
                    .addComponent(IngresoDirectorPelReg, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                    .addComponent(IngresoTituloPelReg)
                    .addGroup(RegistroPeliculasLayout.createSequentialGroup()
                        .addGroup(RegistroPeliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelDirectorPelReg)
                            .addComponent(LabelTituloPelReg)
                            .addComponent(LabelResumenPelReg)
                            .addComponent(LabelFechaPelReg))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        RegistroPeliculasLayout.setVerticalGroup(
            RegistroPeliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroPeliculasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelTituloPelReg)
                .addGap(1, 1, 1)
                .addComponent(IngresoTituloPelReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelResumenPelReg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(LabelFechaPelReg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IngresoFechaPelReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelDirectorPelReg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IngresoDirectorPelReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        BuscarPelículas.setText("Buscar");
        BuscarPelículas.setToolTipText("");
        BuscarPelículas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarPelículasActionPerformed(evt);
            }
        });

        ActualizarPeliculas.setText("Actualizar");
        ActualizarPeliculas.setToolTipText("");
        ActualizarPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarPeliculasActionPerformed(evt);
            }
        });

        RegistrarPeliculas.setText("Registrar");
        RegistrarPeliculas.setToolTipText("");
        RegistrarPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarPeliculasActionPerformed(evt);
            }
        });

        EliminarPeliculas.setText("Eliminar");
        EliminarPeliculas.setToolTipText("");
        EliminarPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarPeliculasActionPerformed(evt);
            }
        });

        InicioPelicula.setText("Volver a Inicio");
        InicioPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioPeliculaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(BuscarPelículas)
                        .addGap(19, 19, 19)
                        .addComponent(ActualizarPeliculas)
                        .addGap(18, 18, 18)
                        .addComponent(RegistrarPeliculas)
                        .addGap(18, 18, 18)
                        .addComponent(EliminarPeliculas))
                    .addComponent(InicioPelicula))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ActualizarPeliculas)
                    .addComponent(RegistrarPeliculas)
                    .addComponent(EliminarPeliculas)
                    .addComponent(BuscarPelículas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InicioPelicula)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PeliculasInterfaceLayout = new javax.swing.GroupLayout(PeliculasInterface);
        PeliculasInterface.setLayout(PeliculasInterfaceLayout);
        PeliculasInterfaceLayout.setHorizontalGroup(
            PeliculasInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PeliculasInterfaceLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(RegistroPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PeliculasInterfaceLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PeliculasInterfaceLayout.setVerticalGroup(
            PeliculasInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PeliculasInterfaceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RegistroPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        RedflixPanel.addTab("Películas", PeliculasInterface);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RedflixPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RedflixPanel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarSeries1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarSeries1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarSeries1ActionPerformed

    private void EliminarPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarPeliculasActionPerformed
        String titulo_pel = IngresoTituloPelReg.getText();
        try {
            Pelicula optionalPelicula = repositorioPelicula.findByTitulo(titulo_pel);
            String BuscarTitulo = optionalPelicula.getTitulo();
            if (BuscarTitulo.equals(titulo_pel)) {
                int id_serie = optionalPelicula.getId_pelicula();
                repositorioPelicula.deleteById(id_serie);
                JOptionPane.showMessageDialog(null, "Se eliminó exitosamente la película: \"" + titulo_pel + "\" ");
                IngresoTituloPelReg.setText("");
                IngresoDirectorPelReg.setText("");
                IngresoFechaPelReg.setText("");
                IngresoResumenPelReg.setText("");

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "La película no fue encontrada");
            IngresoTituloSerReg.setText("");
        }
    }//GEN-LAST:event_EliminarPeliculasActionPerformed

    private void ActualizarPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarPeliculasActionPerformed
        String titulo_pel = IngresoTituloPelReg.getText();
        try {
            Pelicula optionalPelicula = repositorioPelicula.findByTitulo(titulo_pel);
            String BuscarTitulo = optionalPelicula.getTitulo();
            if (BuscarTitulo.equals(titulo_pel)) {
                Pelicula pelicula = repositorioPelicula.findByTitulo(titulo_pel);
                pelicula.setResumen(IngresoResumenPelReg.getText());
                pelicula.setAnio(IngresoFechaPelReg.getText());
                pelicula.setDirector(IngresoDirectorPelReg.getText());
                pelicula = repositorioPelicula.save(pelicula);
                JOptionPane.showMessageDialog(null, "La película \"" + titulo_pel +"\" ha sido actualizada con éxito.");
                IngresoTituloPelReg.setText("");
                IngresoResumenPelReg.setText("");
                IngresoFechaPelReg.setText("");
                IngresoDirectorPelReg.setText("");
            }
        }

        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Los cambios no fueron guardados");
        }
    }//GEN-LAST:event_ActualizarPeliculasActionPerformed

    private void RegistrarPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarPeliculasActionPerformed
        String titulo_pel = IngresoTituloPelReg.getText();
        Pelicula optionalPelicula = repositorioPelicula.findByTitulo(titulo_pel);
        if (optionalPelicula == null){
            Pelicula newPelicula = new Pelicula();
            newPelicula.setTitulo(IngresoTituloPelReg.getText());
            newPelicula.setResumen(IngresoResumenPelReg.getText());
            newPelicula.setAnio(IngresoFechaPelReg.getText());
            newPelicula.setDirector(IngresoDirectorPelReg.getText());

            repositorioPelicula.save(newPelicula);
            JOptionPane.showMessageDialog(null, "Se registró correctamente la película: \"" + titulo_pel + "\"");
            IngresoTituloPelReg.setText("");
            IngresoResumenPelReg.setText("");
            IngresoFechaPelReg.setText("");
            IngresoDirectorPelReg.setText("");
        }else {
            JOptionPane.showMessageDialog(null, "La pelicula ya existe.");
            IngresoTituloSerReg.setText("");
        }
    }//GEN-LAST:event_RegistrarPeliculasActionPerformed

    private void BuscarPelículasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarPelículasActionPerformed
        String titulo = IngresoTituloPelReg.getText();
        try {
            Pelicula optionalPelicula = repositorioPelicula.findByTitulo(titulo);
            String BuscarTitulo = optionalPelicula.getTitulo();
            if (BuscarTitulo.equals(titulo)) {
                JOptionPane.showMessageDialog(null, "Película disponible: " + BuscarTitulo
                    + " fue lanzada en " + optionalPelicula.getAnio()+ " por el director "
                    + optionalPelicula.getDirector());

                IngresoTituloPelReg.setText(optionalPelicula.getTitulo());
                IngresoResumenPelReg.setText(optionalPelicula.getResumen());
                IngresoFechaPelReg.setText(optionalPelicula.getAnio());
                IngresoDirectorPelReg.setText(optionalPelicula.getDirector());
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "La película no fue encontrada");
            IngresoTituloPelReg.setText("");
            IngresoResumenPelReg.setText("");
            IngresoFechaPelReg.setText("");
            IngresoDirectorPelReg.setText("");
        }
    }//GEN-LAST:event_BuscarPelículasActionPerformed

    private void AgregarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarPeliculaActionPerformed
        RedflixPanel.setSelectedIndex(2);
    }//GEN-LAST:event_AgregarPeliculaActionPerformed

    private void AgregarSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarSerieActionPerformed
        RedflixPanel.setSelectedIndex(1);
    }//GEN-LAST:event_AgregarSerieActionPerformed

    private void EliminarSeriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarSeriesActionPerformed

        String titulo = IngresoTituloSerReg.getText();
        try {
            Serie optionalSerie = repositorioSerie.findByTitulo(titulo);
            String BuscarTitulo = optionalSerie.getTitulo();
            if (BuscarTitulo.equals(titulo)) {
                int id_serie = optionalSerie.getId();
                repositorioSerie.deleteById(id_serie);
                JOptionPane.showMessageDialog(null, "La serie \"" + titulo + "\" ha sido eliminada exitosamente.");
                IngresoTituloSerReg.setText("");
                IngresoEpisodiosSerReg.setText("");
                IngresoTemporadasSerReg.setText("");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "La serie no fue encontrada");
            IngresoTituloSerReg.setText("");
        }
    }//GEN-LAST:event_EliminarSeriesActionPerformed

    private void RegistrarSeriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarSeriesActionPerformed

        String titulo = IngresoTituloSerReg.getText();
        Serie optionalSerie = repositorioSerie.findByTitulo(titulo);
        if (optionalSerie == null){
            Serie newSerie = new Serie();
            newSerie.setTitulo(IngresoTituloSerReg.getText());
            newSerie.setTemporadas(Long.parseLong(IngresoTemporadasSerReg.getText()));
            newSerie.setEpisodios(Long.parseLong(IngresoEpisodiosSerReg.getText()));
            repositorioSerie.save(newSerie);
            JOptionPane.showMessageDialog(null, "Se registró correctamente la serie: \"" + titulo + "\"");
            IngresoTituloSerReg.setText("");
            IngresoEpisodiosSerReg.setText("");
            IngresoTemporadasSerReg.setText("");
        }else {
            JOptionPane.showMessageDialog(null, "La serie ya existe.");
            IngresoTituloSerReg.setText("");
        }
    }//GEN-LAST:event_RegistrarSeriesActionPerformed

    private void ActualizarSeriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarSeriesActionPerformed

        String titulo = IngresoTituloSerReg.getText();
        Long temporadas = Long.parseLong(IngresoTemporadasSerReg.getText());
        Long episodios = Long.parseLong(IngresoEpisodiosSerReg.getText());
        try {
            Serie optionalSerie = repositorioSerie.findByTitulo(titulo);
            String BuscarTitulo = optionalSerie.getTitulo();
            if (BuscarTitulo.equals(titulo)) {
                Serie serie = repositorioSerie.findByTitulo(titulo);
                serie.setTemporadas(temporadas);
                serie.setEpisodios(episodios);
                serie = repositorioSerie.save(serie);
                JOptionPane.showMessageDialog(null, "La serie \"" + titulo +"\" ha sido actualizada con éxito.");
                IngresoTituloSerReg.setText("");
                IngresoTemporadasSerReg.setText("");
                IngresoEpisodiosSerReg.setText("");
            }
        }

        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Los cambios no fueron guardados");
        }
    }//GEN-LAST:event_ActualizarSeriesActionPerformed

    private void BuscarSeriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarSeriesActionPerformed

        String titulo = IngresoTituloSerReg.getText();
        try {
            Serie optionalSerie = repositorioSerie.findByTitulo(titulo);
            String BuscarTitulo = optionalSerie.getTitulo();
            if (BuscarTitulo.equals(titulo)) {
                JOptionPane.showMessageDialog(null, "Serie disponible: " + BuscarTitulo
                    + " consta de " + optionalSerie.getEpisodios() + " episodios en "
                    + optionalSerie.getTemporadas() + " temporadas");
                IngresoEpisodiosSerReg.setText(optionalSerie.getEpisodios().toString());
                IngresoTemporadasSerReg.setText(optionalSerie.getTemporadas().toString());
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "La serie que busca no fue encontrada");
            IngresoTituloSerReg.setText("");
            IngresoEpisodiosSerReg.setText("");
            IngresoTemporadasSerReg.setText("");
        }
    }//GEN-LAST:event_BuscarSeriesActionPerformed

    private void InicioSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioSerieActionPerformed
        RedflixPanel.setSelectedIndex(0);
    }//GEN-LAST:event_InicioSerieActionPerformed

    private void InicioPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioPeliculaActionPerformed
        RedflixPanel.setSelectedIndex(0);
    }//GEN-LAST:event_InicioPeliculaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RedflixForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RedflixForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RedflixForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RedflixForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame frame = new JFrame("App");
                frame.setContentPane(new RedflixForm().RedflixPanel);
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.pack();
                new RedflixForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarPeliculas;
    private javax.swing.JButton ActualizarSeries;
    private javax.swing.JButton AgregarPelicula;
    private javax.swing.JButton AgregarSerie;
    private javax.swing.JButton BuscarPelículas;
    private javax.swing.JButton BuscarSeries;
    private javax.swing.JButton BuscarSeries1;
    private javax.swing.JButton EliminarPeliculas;
    private javax.swing.JButton EliminarSeries;
    private javax.swing.JLabel Imagen;
    private javax.swing.JTextField IngresoDirectorPelReg;
    private javax.swing.JTextField IngresoEpisodiosSerReg;
    private javax.swing.JTextField IngresoFechaPelReg;
    private javax.swing.JTextArea IngresoResumenPelReg;
    private javax.swing.JTextField IngresoTemporadasSerReg;
    private javax.swing.JTextField IngresoTituloPelReg;
    private javax.swing.JTextField IngresoTituloSerReg;
    private javax.swing.JPanel Inicio;
    private javax.swing.JButton InicioPelicula;
    private javax.swing.JButton InicioSerie;
    private javax.swing.JLabel Intro;
    private javax.swing.JLabel LabelDirectorPelReg;
    private javax.swing.JLabel LabelEpisodiosSerReg;
    private javax.swing.JLabel LabelFechaPelReg;
    private javax.swing.JLabel LabelResumenPelReg;
    private javax.swing.JLabel LabelTemporadaSerReg;
    private javax.swing.JLabel LabelTituloPelReg;
    private javax.swing.JLabel LabelTituloSerReg;
    private javax.swing.JPanel PeliculasInterface;
    private javax.swing.JTabbedPane RedflixPanel;
    private javax.swing.JButton RegistrarPeliculas;
    private javax.swing.JButton RegistrarSeries;
    private javax.swing.JPanel RegistroPeliculas;
    private javax.swing.JPanel RegistroSeries;
    private javax.swing.JPanel SeriesInterface;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

   
}
